name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run lint (代替扫描)
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Build project
        run: npm run build

      - name: Package dist as zip
        run: |
          zip -r dist.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-todos-dist
          path: dist.zip